// <auto-generated />
using System;
using ClinicalPatientPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicalPatientPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818171120_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicalPatientPortal.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AlertId");

                    b.HasIndex("PatientId");

                    b.ToTable("Alerts");

                    b.HasData(
                        new
                        {
                            AlertId = 1,
                            AlertType = "Drug Allergy",
                            CreatedDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Severe penicillin allergy - avoid penicillin-class antibiotics",
                            PatientId = 1,
                            Severity = "Critical"
                        },
                        new
                        {
                            AlertId = 2,
                            AlertType = "Bleeding Precaution",
                            CreatedDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Patient on Warfarin - monitor for bleeding, check INR before procedures",
                            PatientId = 1,
                            Severity = "High"
                        },
                        new
                        {
                            AlertId = 3,
                            AlertType = "Fall Risk",
                            CreatedDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "History of falls - use bed alarm and non-slip footwear",
                            PatientId = 2,
                            Severity = "Medium"
                        },
                        new
                        {
                            AlertId = 4,
                            AlertType = "Cardiac Monitoring",
                            CreatedDate = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Patient on statin + antihypertensive combination - monitor blood pressure regularly",
                            PatientId = 4,
                            Severity = "Medium"
                        },
                        new
                        {
                            AlertId = 5,
                            AlertType = "DNR",
                            CreatedDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Confirmed Do Not Resuscitate order on file",
                            PatientId = 6,
                            Severity = "Critical"
                        },
                        new
                        {
                            AlertId = 6,
                            AlertType = "Fall Risk",
                            CreatedDate = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elderly patient with mobility issues - use walker, supervise transfers",
                            PatientId = 6,
                            Severity = "High"
                        },
                        new
                        {
                            AlertId = 7,
                            AlertType = "Isolation Precautions",
                            CreatedDate = new DateTime(2021, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Contact precautions - MRSA colonization on record",
                            PatientId = 8,
                            Severity = "Medium"
                        },
                        new
                        {
                            AlertId = 8,
                            AlertType = "Drug Allergy",
                            CreatedDate = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Severe latex allergy - use latex-free equipment for all procedures",
                            PatientId = 10,
                            Severity = "High"
                        });
                });

            modelBuilder.Entity("ClinicalPatientPortal.Models.Allergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergyId"));

                    b.Property<string>("AllergyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AllergyId");

                    b.HasIndex("PatientId");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            AllergyId = 1,
                            AllergyName = "Penicillin",
                            PatientId = 1,
                            RecordedDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Severe",
                            Status = "Active"
                        },
                        new
                        {
                            AllergyId = 2,
                            AllergyName = "Latex",
                            PatientId = 1,
                            RecordedDate = new DateTime(2021, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Moderate",
                            Status = "Active"
                        },
                        new
                        {
                            AllergyId = 3,
                            AllergyName = "Sulfa Drugs",
                            PatientId = 2,
                            RecordedDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Mild",
                            Status = "Active"
                        },
                        new
                        {
                            AllergyId = 4,
                            AllergyName = "Peanuts",
                            PatientId = 3,
                            RecordedDate = new DateTime(2015, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Severe",
                            Status = "Active"
                        },
                        new
                        {
                            AllergyId = 5,
                            AllergyName = "Aspirin",
                            PatientId = 4,
                            RecordedDate = new DateTime(2018, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Moderate",
                            Status = "Active"
                        },
                        new
                        {
                            AllergyId = 6,
                            AllergyName = "Shellfish",
                            PatientId = 4,
                            RecordedDate = new DateTime(2016, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Mild",
                            Status = "Resolved"
                        },
                        new
                        {
                            AllergyId = 7,
                            AllergyName = "Iodine Contrast",
                            PatientId = 6,
                            RecordedDate = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Severe",
                            Status = "Active"
                        },
                        new
                        {
                            AllergyId = 8,
                            AllergyName = "Codeine",
                            PatientId = 7,
                            RecordedDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Moderate",
                            Status = "Active"
                        },
                        new
                        {
                            AllergyId = 9,
                            AllergyName = "Penicillin",
                            PatientId = 8,
                            RecordedDate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Mild",
                            Status = "Active"
                        },
                        new
                        {
                            AllergyId = 10,
                            AllergyName = "Latex",
                            PatientId = 10,
                            RecordedDate = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Severe",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ClinicalPatientPortal.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            DocumentId = 1,
                            DocumentDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Consent Form.pdf",
                            DocumentType = "PDF",
                            FilePath = "/documents/patient1/consent-form.pdf",
                            PatientId = 1,
                            UploadedDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 2,
                            DocumentDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Lab Results.pdf",
                            DocumentType = "PDF",
                            FilePath = "/documents/patient1/lab-results.pdf",
                            PatientId = 1,
                            UploadedDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 3,
                            DocumentDate = new DateTime(2022, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Referral Letter.docx",
                            DocumentType = "Word Document",
                            FilePath = "/documents/patient2/referral-letter.docx",
                            PatientId = 2,
                            UploadedDate = new DateTime(2022, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 4,
                            DocumentDate = new DateTime(2021, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Immunization Record.pdf",
                            DocumentType = "PDF",
                            FilePath = "/documents/patient3/immunization-record.pdf",
                            PatientId = 3,
                            UploadedDate = new DateTime(2021, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 5,
                            DocumentDate = new DateTime(2022, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Discharge Summary.pdf",
                            DocumentType = "PDF",
                            FilePath = "/documents/patient4/discharge-summary.pdf",
                            PatientId = 4,
                            UploadedDate = new DateTime(2022, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 6,
                            DocumentDate = new DateTime(2023, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Insurance Card.jpg",
                            DocumentType = "Image",
                            FilePath = "/documents/patient5/insurance-card.jpg",
                            PatientId = 5,
                            UploadedDate = new DateTime(2023, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 7,
                            DocumentDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Advance Directive.pdf",
                            DocumentType = "PDF",
                            FilePath = "/documents/patient6/advance-directive.pdf",
                            PatientId = 6,
                            UploadedDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 8,
                            DocumentDate = new DateTime(2022, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "X-Ray Image.jpg",
                            DocumentType = "Image",
                            FilePath = "/documents/patient7/xray-image.jpg",
                            PatientId = 7,
                            UploadedDate = new DateTime(2022, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 9,
                            DocumentDate = new DateTime(2023, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Progress Notes.docx",
                            DocumentType = "Word Document",
                            FilePath = "/documents/patient8/progress-notes.docx",
                            PatientId = 8,
                            UploadedDate = new DateTime(2023, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 10,
                            DocumentDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Consent Form.pdf",
                            DocumentType = "PDF",
                            FilePath = "/documents/patient9/consent-form.pdf",
                            PatientId = 9,
                            UploadedDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = 11,
                            DocumentDate = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentName = "Lab Results.pdf",
                            DocumentType = "PDF",
                            FilePath = "/documents/patient10/lab-results.pdf",
                            PatientId = 10,
                            UploadedDate = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ClinicalPatientPortal.Models.Medication", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationId"));

                    b.Property<string>("DosageInstructions")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PrescribingProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Route")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Strength")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MedicationId");

                    b.HasIndex("PatientId");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            MedicationId = 1,
                            DosageInstructions = "Take one tablet daily",
                            Frequency = "Once daily",
                            MedicationName = "Warfarin",
                            PatientId = 1,
                            PrescribingProvider = "Dr. Alan Carter",
                            Route = "Oral",
                            StartDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "5mg"
                        },
                        new
                        {
                            MedicationId = 2,
                            DosageInstructions = "Take twice daily with food",
                            Frequency = "Twice daily",
                            MedicationName = "Metformin",
                            PatientId = 1,
                            PrescribingProvider = "Dr. Alan Carter",
                            Route = "Oral",
                            StartDate = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "500mg"
                        },
                        new
                        {
                            MedicationId = 3,
                            DosageInstructions = "Take one tablet daily",
                            Frequency = "Once daily",
                            MedicationName = "Lisinopril",
                            PatientId = 2,
                            PrescribingProvider = "Dr. Susan Lee",
                            Route = "Oral",
                            StartDate = new DateTime(2021, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "10mg"
                        },
                        new
                        {
                            MedicationId = 4,
                            DosageInstructions = "2 puffs as needed for wheezing",
                            Frequency = "As needed",
                            MedicationName = "Albuterol Inhaler",
                            PatientId = 3,
                            PrescribingProvider = "Dr. Karen Wu",
                            Route = "Inhalation",
                            StartDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "90mcg"
                        },
                        new
                        {
                            MedicationId = 5,
                            DosageInstructions = "Take one tablet at bedtime",
                            Frequency = "Once daily",
                            MedicationName = "Atorvastatin",
                            PatientId = 4,
                            PrescribingProvider = "Dr. Alan Carter",
                            Route = "Oral",
                            StartDate = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "20mg"
                        },
                        new
                        {
                            MedicationId = 6,
                            DosageInstructions = "Take one tablet daily",
                            Frequency = "Once daily",
                            MedicationName = "Amlodipine",
                            PatientId = 4,
                            PrescribingProvider = "Dr. Alan Carter",
                            Route = "Oral",
                            StartDate = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "5mg"
                        },
                        new
                        {
                            MedicationId = 7,
                            DosageInstructions = "Take one tablet in the morning",
                            Frequency = "Once daily",
                            MedicationName = "Sertraline",
                            PatientId = 5,
                            PrescribingProvider = "Dr. Maria Gomez",
                            Route = "Oral",
                            StartDate = new DateTime(2023, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "50mg"
                        },
                        new
                        {
                            MedicationId = 8,
                            DosageInstructions = "Take one tablet twice daily",
                            Frequency = "Twice daily",
                            MedicationName = "Metoprolol",
                            PatientId = 6,
                            PrescribingProvider = "Dr. Susan Lee",
                            Route = "Oral",
                            StartDate = new DateTime(2017, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "25mg"
                        },
                        new
                        {
                            MedicationId = 9,
                            DosageInstructions = "Take one tablet in the morning",
                            Frequency = "Once daily",
                            MedicationName = "Furosemide",
                            PatientId = 6,
                            PrescribingProvider = "Dr. Susan Lee",
                            Route = "Oral",
                            StartDate = new DateTime(2018, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "20mg"
                        },
                        new
                        {
                            MedicationId = 10,
                            DosageInstructions = "Take on an empty stomach each morning",
                            Frequency = "Once daily",
                            MedicationName = "Levothyroxine",
                            PatientId = 7,
                            PrescribingProvider = "Dr. Karen Wu",
                            Route = "Oral",
                            StartDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "75mcg"
                        },
                        new
                        {
                            MedicationId = 11,
                            DosageInstructions = "Take one capsule before breakfast",
                            Frequency = "Once daily",
                            MedicationName = "Omeprazole",
                            PatientId = 8,
                            PrescribingProvider = "Dr. Maria Gomez",
                            Route = "Oral",
                            StartDate = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "20mg"
                        },
                        new
                        {
                            MedicationId = 12,
                            DosageInstructions = "Take as needed for pain, max 3x daily",
                            Frequency = "As needed",
                            MedicationName = "Ibuprofen",
                            PatientId = 9,
                            PrescribingProvider = "Dr. Alan Carter",
                            Route = "Oral",
                            StartDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "400mg"
                        },
                        new
                        {
                            MedicationId = 13,
                            DosageInstructions = "Inject 20 units subcutaneously at bedtime",
                            Frequency = "Once daily",
                            MedicationName = "Insulin Glargine",
                            PatientId = 10,
                            PrescribingProvider = "Dr. Susan Lee",
                            Route = "Subcutaneous",
                            StartDate = new DateTime(2020, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Strength = "100 units/mL"
                        });
                });

            modelBuilder.Entity("ClinicalPatientPortal.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            AddressLine1 = "123 Maple St",
                            City = "Springfield",
                            DOB = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            Gender = "Female",
                            LastName = "Doe",
                            MRN = "MRN1001",
                            PhoneNumber = "555-123-4567",
                            State = "IL",
                            ZipCode = "62701"
                        },
                        new
                        {
                            PatientId = 2,
                            AddressLine1 = "456 Oak Ave",
                            City = "Springfield",
                            DOB = new DateTime(1978, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Smith",
                            MRN = "MRN1002",
                            PhoneNumber = "555-987-6543",
                            State = "IL",
                            ZipCode = "62702"
                        },
                        new
                        {
                            PatientId = 3,
                            AddressLine1 = "789 Pine Rd",
                            City = "Springfield",
                            DOB = new DateTime(1992, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            Gender = "Female",
                            LastName = "Johnson",
                            MRN = "MRN1003",
                            PhoneNumber = "555-222-3333",
                            State = "IL",
                            ZipCode = "62703"
                        },
                        new
                        {
                            PatientId = 4,
                            AddressLine1 = "12 Elm St",
                            City = "Chicago",
                            DOB = new DateTime(1965, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            Gender = "Male",
                            LastName = "Brown",
                            MRN = "MRN1004",
                            PhoneNumber = "555-333-1111",
                            State = "IL",
                            ZipCode = "60601"
                        },
                        new
                        {
                            PatientId = 5,
                            AddressLine1 = "88 Birch Blvd",
                            City = "Chicago",
                            DOB = new DateTime(2001, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            Gender = "Female",
                            LastName = "Davis",
                            MRN = "MRN1005",
                            PhoneNumber = "555-444-2222",
                            State = "IL",
                            ZipCode = "60602"
                        },
                        new
                        {
                            PatientId = 6,
                            AddressLine1 = "34 Cedar Ct",
                            City = "Peoria",
                            DOB = new DateTime(1955, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            Gender = "Male",
                            LastName = "Wilson",
                            MRN = "MRN1006",
                            PhoneNumber = "555-555-3333",
                            State = "IL",
                            ZipCode = "61601"
                        },
                        new
                        {
                            PatientId = 7,
                            AddressLine1 = "56 Walnut Way",
                            City = "Peoria",
                            DOB = new DateTime(1988, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linda",
                            Gender = "Female",
                            LastName = "Martinez",
                            MRN = "MRN1007",
                            PhoneNumber = "555-666-4444",
                            State = "IL",
                            ZipCode = "61602"
                        },
                        new
                        {
                            PatientId = 8,
                            AddressLine1 = "90 Spruce Dr",
                            City = "Naperville",
                            DOB = new DateTime(1972, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            Gender = "Male",
                            LastName = "Anderson",
                            MRN = "MRN1008",
                            PhoneNumber = "555-777-5555",
                            State = "IL",
                            ZipCode = "60540"
                        },
                        new
                        {
                            PatientId = 9,
                            AddressLine1 = "21 Willow Ln",
                            City = "Naperville",
                            DOB = new DateTime(1995, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Patricia",
                            Gender = "Female",
                            LastName = "Thomas",
                            MRN = "MRN1009",
                            PhoneNumber = "555-888-6666",
                            State = "IL",
                            ZipCode = "60541"
                        },
                        new
                        {
                            PatientId = 10,
                            AddressLine1 = "67 Aspen Ave",
                            City = "Aurora",
                            DOB = new DateTime(1960, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            Gender = "Male",
                            LastName = "Taylor",
                            MRN = "MRN1010",
                            PhoneNumber = "555-999-7777",
                            State = "IL",
                            ZipCode = "60505"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicalPatientPortal.Models.Alert", b =>
                {
                    b.HasOne("ClinicalPatientPortal.Models.Patient", "Patient")
                        .WithMany("Alerts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalPatientPortal.Models.Allergy", b =>
                {
                    b.HasOne("ClinicalPatientPortal.Models.Patient", "Patient")
                        .WithMany("Allergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalPatientPortal.Models.Document", b =>
                {
                    b.HasOne("ClinicalPatientPortal.Models.Patient", "Patient")
                        .WithMany("Documents")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalPatientPortal.Models.Medication", b =>
                {
                    b.HasOne("ClinicalPatientPortal.Models.Patient", "Patient")
                        .WithMany("Medications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicalPatientPortal.Models.Patient", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Allergies");

                    b.Navigation("Documents");

                    b.Navigation("Medications");
                });
#pragma warning restore 612, 618
        }
    }
}
